import { Horse } from "./types";

export const sampleHorses: Horse[] = [
  {
    id: "1",
    name: "サンライズスター",
    status: "術後入院",
    exercise: "完全舎飼い",
    firstVisitDate: "2026-03-15",
    diagnosis: "右前脚跛行",
    notes: "消炎処置継続中。歩様に注意すること。",
    records: [
      { id: "r1-1", date: "2026-03-15", condition: "跛行あり（右前）", veterinarian: "山田獣医師", treatment: "消炎剤投与・冷却療法", medication: "フェニルブタゾン 4g / 日", notes: "4日間継続投与。右前肢に発熱・腫脹を確認。体温38.8℃。" },
      { id: "r1-2", date: "2026-03-18", condition: "腫脹は少し引いている", notes: "厩舎スタッフより。歩様はまだ気になるとのこと。" },
      { id: "r1-3", date: "2026-03-22", condition: "軽度改善", veterinarian: "山田獣医師", treatment: "レーザー治療・外用消炎", medication: "ジクロフェナクゲル", notes: "腫脹は引いてきているが歩様異常継続。週3回実施。" },
      { id: "r1-4", date: "2026-03-28", condition: "食欲あり、歩様は継続注意", notes: "厩舎スタッフより。元気はある。" },
      { id: "r1-5", date: "2026-04-01", condition: "改善傾向", veterinarian: "山田獣医師", treatment: "経過確認・継続処置", notes: "軽速歩にて跛行あり。引き続き経過観察。" },
    ],
    weightRecords: [
      { id: "w1-1", date: "2026-03-15", weight: 468.5 },
      { id: "w1-2", date: "2026-03-22", weight: 465.0 },
      { id: "w1-3", date: "2026-03-29", weight: 463.5 },
      { id: "w1-4", date: "2026-04-05", weight: 464.0 },
    ],
    temperatureRecords: [
      { id: "t1-1", date: "2026-03-15", temperature: 38.8, notes: "右前肢に熱感あり" },
      { id: "t1-2", date: "2026-03-18", temperature: 38.3 },
      { id: "t1-3", date: "2026-03-22", temperature: 38.0 },
      { id: "t1-4", date: "2026-03-28", temperature: 37.9 },
      { id: "t1-5", date: "2026-04-01", temperature: 37.8 },
    ],
    bloodTestRecords: [
      { id: "b1-1", date: "2026-03-15", items: [
        { key: "WBC", label: "白血球数 (WBC)", value: 11.2, unit: "10^3/μL", flagged: true },
        { key: "Fib", label: "フィブリノーゲン (Fib)", value: 420, unit: "mg/dL", flagged: true },
        { key: "TP", label: "総蛋白 (TP)", value: 7.1, unit: "g/dL" },
      ] },
      { id: "b1-2", date: "2026-03-22", items: [
        { key: "WBC", label: "白血球数 (WBC)", value: 9.4, unit: "10^3/μL" },
        { key: "Fib", label: "フィブリノーゲン (Fib)", value: 350, unit: "mg/dL", flagged: true },
        { key: "TP", label: "総蛋白 (TP)", value: 7.0, unit: "g/dL" },
      ] },
      { id: "b1-3", date: "2026-04-01", items: [
        { key: "WBC", label: "白血球数 (WBC)", value: 8.1, unit: "10^3/μL" },
        { key: "Fib", label: "フィブリノーゲン (Fib)", value: 280, unit: "mg/dL" },
        { key: "TP", label: "総蛋白 (TP)", value: 6.9, unit: "g/dL" },
      ] },
    ],
    feedingRecords: [
      { id: "f1-1", date: "2026-03-15", content: "乾草のみ（禁食明け・少量ずつ）" },
      { id: "f1-2", date: "2026-03-20", content: "配合飼料1kg + 乾草4kg（1日2回）" },
      { id: "f1-3", date: "2026-04-01", content: "配合飼料2kg + 乾草4kg（1日2回）" },
    ],
  },
  {
    id: "2",
    name: "ムーンライトソナタ",
    status: "術後入院",
    exercise: "引き運動",
    firstVisitDate: "2026-03-28",
    diagnosis: "消化器疾患（疝痛）",
    notes: "経鼻胃管にて胃洗浄実施済み。腸音に注意。",
    records: [
      { id: "r2-1", date: "2026-03-28", condition: "腹痛症状", veterinarian: "鈴木獣医師", treatment: "胃洗浄・輸液療法", medication: "リンゲル液 5L・ブスコパン 20mg", notes: "前肢で地面をかく動作あり。腸音減弱。" },
      { id: "r2-2", date: "2026-03-29", condition: "腸音回復。採食再開。排便確認", notes: "厩舎スタッフより。朝から食欲戻ってきた。" },
      { id: "r2-3", date: "2026-04-05", condition: "良好", veterinarian: "鈴木獣医師", treatment: "経過確認", notes: "食欲・排便ともに正常。継続管理。" },
    ],
  },
  {
    id: "3",
    name: "ゴールデンフラッシュ",
    status: "術後入院",
    exercise: "完全舎飼い",
    firstVisitDate: "2026-04-01",
    diagnosis: "蹄葉炎（軽度）",
    notes: "蹄底に圧痛あり。安静管理中。柔らかい床材使用。",
    records: [
      { id: "r3-1", date: "2026-04-01", condition: "蹄部疼痛", veterinarian: "山田獣医師", treatment: "蹄浴・NSAID投与", medication: "メロキシカム 0.6mg/kg", notes: "5日間投与。安静管理継続。両前肢蹄底に圧痛。" },
      { id: "r3-2", date: "2026-04-04", condition: "安静にしている。食欲普通", notes: "厩舎スタッフより。おとなしい。" },
      { id: "r3-3", date: "2026-04-08", condition: "安定", veterinarian: "山田獣医師", treatment: "経過確認・蹄浴継続", notes: "疼痛スコア改善傾向。食欲あり。" },
    ],
  },
  {
    id: "4",
    name: "シルバーウィンド",
    status: "術後入院",
    exercise: "引き運動",
    firstVisitDate: "2026-04-05",
    diagnosis: "上気道炎",
    notes: "鼻漏・咳あり。隔離管理中。他馬への接触を避けること。",
    records: [
      { id: "r4-1", date: "2026-04-05", condition: "鼻漏・咳嗽", veterinarian: "鈴木獣医師", treatment: "抗生物質・解熱剤投与", medication: "エンロフロキサシン 7.5mg/kg / フェニルブタゾン 2g", notes: "体温39.1℃。漿液性鼻漏、乾性咳嗽あり。" },
      { id: "r4-2", date: "2026-04-07", condition: "咳は少し減った気がする", notes: "厩舎スタッフより。鼻水はまだ出ている。" },
      { id: "r4-3", date: "2026-04-10", condition: "微改善", veterinarian: "鈴木獣医師", treatment: "経過確認・投薬継続", notes: "体温38.6℃。鼻漏継続するが咳嗽は減少。" },
    ],
  },
  {
    id: "5",
    name: "スターダスト",
    status: "術後入院",
    exercise: "サンシャインパドック",
    firstVisitDate: "2026-02-10",
    diagnosis: "筋肉疲労・軽度筋炎",
    notes: "運動量を制限中。リハビリ運動のみ可。",
    records: [
      { id: "r5-1", date: "2026-02-10", condition: "後肢筋肉硬直", veterinarian: "山田獣医師", treatment: "マッサージ・温浴療法", medication: "ビタミンE 1000IU・セレン 1mg", notes: "トレーニング後に発症。患部に熱感あり。" },
      { id: "r5-2", date: "2026-02-15", condition: "硬直は和らいできた", notes: "厩舎スタッフより。元気はある。" },
      { id: "r5-3", date: "2026-02-20", condition: "改善", veterinarian: "山田獣医師", treatment: "経過確認", notes: "硬直は解消。常歩運動のみ可。" },
      { id: "r5-4", date: "2026-03-05", condition: "ほぼ正常", veterinarian: "山田獣医師", treatment: "リハビリ確認", notes: "速歩可能となった。あと2週間経過観察。" },
    ],
  },
  {
    id: "6",
    name: "レインボーブリッジ",
    status: "術後入院",
    exercise: "サンシャインパドック",
    firstVisitDate: "2026-02-20",
    diagnosis: "皮膚炎（腹部）",
    notes: "腹部の発疹は改善傾向。週1回の経過確認中。",
    records: [
      { id: "r6-1", date: "2026-02-20", condition: "腹部発疹", veterinarian: "鈴木獣医師", treatment: "局所ステロイド塗布・抗ヒスタミン投与", medication: "ベタメタゾン軟膏・クロルフェニラミン", notes: "紅斑・丘疹を腹部全体に確認。掻痒あり。" },
      { id: "r6-2", date: "2026-02-25", condition: "掻痒は少し落ち着いている", notes: "厩舎スタッフより。かきむしる回数が減った。" },
      { id: "r6-3", date: "2026-03-01", condition: "改善中", veterinarian: "鈴木獣医師", treatment: "経過確認・塗布継続", notes: "発疹の縮小を確認。掻痒は軽減。" },
      { id: "r6-4", date: "2026-03-15", condition: "ほぼ回復", veterinarian: "鈴木獣医師", treatment: "経過確認", notes: "発疹はほぼ消失。皮膚状態良好。" },
    ],
  },
  {
    id: "7",
    name: "ダイヤモンドスター",
    status: "術後入院",
    exercise: "引き運動",
    firstVisitDate: "2026-03-01",
    diagnosis: "軽度跛行（回復期）",
    notes: "右後肢。リハビリ運動中。速歩まで可。",
    records: [
      { id: "r7-1", date: "2026-03-01", condition: "右後肢跛行", veterinarian: "山田獣医師", treatment: "冷却・テーピング固定", medication: "ジクロフェナク外用ゲル", notes: "打撲による跛行。患部に軽度腫脹。" },
      { id: "r7-2", date: "2026-03-08", condition: "大人しくしている", notes: "厩舎スタッフより。特に問題なさそう。" },
      { id: "r7-3", date: "2026-03-15", condition: "改善", veterinarian: "山田獣医師", treatment: "リハビリ確認", notes: "常歩にて跛行ほぼなし。速歩で軽度残存。" },
    ],
  },
  {
    id: "8",
    name: "オーシャンブリーズ",
    status: "術後入院",
    exercise: "サンシャインパドック",
    firstVisitDate: "2026-03-05",
    diagnosis: "結膜炎（左眼）",
    notes: "点眼薬継続中。週2回の状態確認。",
    records: [
      { id: "r8-1", date: "2026-03-05", condition: "左眼充血・流涙", veterinarian: "鈴木獣医師", treatment: "眼洗浄・点眼処置", medication: "抗生物質点眼薬（1日4回）・人工涙液", notes: "角膜に軽微な混濁あり。流涙多量。" },
      { id: "r8-2", date: "2026-03-09", condition: "目やには出ているが落ち着いている", notes: "厩舎スタッフより。嫌がらずに点眼できている。" },
      { id: "r8-3", date: "2026-03-15", condition: "改善中", veterinarian: "鈴木獣医師", treatment: "経過確認・点眼継続", notes: "充血軽減。混濁消失。流涙は継続。" },
      { id: "r8-4", date: "2026-04-01", condition: "ほぼ正常", veterinarian: "鈴木獣医師", treatment: "経過確認", notes: "流涙もほぼなし。もう1週間継続確認。" },
    ],
  },
  {
    id: "9",
    name: "サンダーボルト",
    status: "譲渡馬",
    exercise: "サンシャインパドック",
    firstVisitDate: "2026-01-10",
    diagnosis: "なし",
    records: [
      { id: "r9-1", date: "2026-01-10", condition: "良好", veterinarian: "山田獣医師", treatment: "初回健康診断", notes: "全身状態良好。異常なし。" },
      { id: "r9-2", date: "2026-02-15", condition: "良好", veterinarian: "山田獣医師", treatment: "定期健診", notes: "体重増加良好。" },
    ],
  },
  {
    id: "10",
    name: "クリスタルムーン",
    status: "譲渡馬",
    exercise: "サンシャインパドック",
    firstVisitDate: "2026-01-10",
    diagnosis: "なし",
    records: [
      { id: "r10-1", date: "2026-01-10", condition: "良好", veterinarian: "鈴木獣医師", treatment: "初回健康診断", notes: "全身状態良好。異常なし。" },
    ],
  },
  {
    id: "11",
    name: "ローズマリーウィンド",
    status: "譲渡馬",
    exercise: "サンシャインパドック",
    firstVisitDate: "2026-01-15",
    diagnosis: "なし",
    records: [
      { id: "r11-1", date: "2026-01-15", condition: "良好", veterinarian: "山田獣医師", treatment: "初回健康診断", notes: "全身状態良好。異常なし。" },
    ],
  },
  {
    id: "12",
    name: "ブルースカイドリーム",
    status: "譲渡馬",
    exercise: "サンシャインパドック",
    firstVisitDate: "2026-01-15",
    diagnosis: "なし",
    records: [
      { id: "r12-1", date: "2026-01-15", condition: "良好", veterinarian: "鈴木獣医師", treatment: "初回健康診断", notes: "全身状態良好。異常なし。" },
    ],
  },
];
